config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root "home#index"

  resources :categories
  resources :transactions

  resources :users
end

app/views/shared/_button.html.erb
<div class="flex justify-center items-center mt-8 fixed bottom-0 p-4 bg-primary left-0 w-full border">
  <%= link_to button_text, button_path, class: "py-3 w-full px-5 bg-blue-600 border-2 uppercase font-medium text-center bg-transparent text-white block font-medium" %>
</div>

app/views/shared/_edit_and_delete_buttons.html.erb
 <div class='flex justify-end w-full items-center gap-4'>
  <%= link_to edit_category_path(category), class: "rounded py-2 px-4 text-white bg-amber-500 bg-amber-400 text-secondary inline-block font-medium" do %>
    <i class="fas fa-edit"></i> Edit
  <% end %>
  <%= button_to category, method: :delete, data: { confirm: "Are you sure you want to delete this category?" }, class: "rounded py-2 cursor-pointer px-4 bg-red-600 text-white inline-block font-medium" do %>
    <i class="fas fa-trash"></i>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class='flex bg-main border-white px-4 text-text-primary text-text-primary justify-between items-center w-full h-[70px]'>
  <% if defined?(back) %>
    <%= link_to 'javascript:history.back()', class: '' do %>
      <i class="fas fa-arrow-left"></i>
    <% end %>
  <% end %>
  
  <h2 class='text-2xl font-medium uppercase'><%= heading %></h2>

  <div class="actions font-medium">
    <% if defined?(signup) && signup %>
      <%= f.submit "Next" %>
    <% end %>

    <% if defined?(login) && login && f %>
      <%= f.submit "Log in" %>
    <% end %>
  </div>
</div>