config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root "home#index"

  resources :categories
  resources :transactions

  resources :users
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :financial_transactions, class_name: 'Transaction'

  has_one_attached :icon

  validates :name, presence: true
  validates :name, format: { with: /\A[a-zA-Z0-9 ]+\z/ }
  validates :name, uniqueness: { scope: :user_id }
  validate :name_is_not_reserved

  def name_is_not_reserved
    errors.add(:name, 'is reserved') if name && %w[admin user guest].include?(name.downcase)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all.order(created_at: :desc)
  end

  def show; end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        puts "Icon attached: #{params[:category][:icon].inspect}" if @category.icon.attached?
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        puts "Errors: #{@category.errors.full_messages.join(', ')}"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    params[:category].delete(:icon) if params[:category][:icon].blank?

    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/views/categories/_category.html.erb
<section class='border-2 block w-full rounded p-2'>  
  <div class='border-amber-500'>
    <%= link_to category, class: "block mb-2 cursor-pointer border-orange-500" do %>
      <div id="<%= dom_id category %>" class='flex justify-between items-center'>
        <div class='flex justify-start items-center w-full gap-4'>
          <div class="h-[70px] w-[70px] border rounded flex justify-center items-center">
            <% if category.icon.attached? %>
              <%= image_tag(url_for(category.icon), alt: "Category Icon", class: "fas fa-user fa-2x h-full w-full object-cover") %>
            <% else %>
              <i class="fas fa-user fa-2x"></i>
            <% end %>
          </div>

          <p class="">
            <%= category.name %>
          </p>
        </div>
        <p><strong>$</strong><%= category.financial_transactions.sum(:amount) %></p>
      </div>
    <% end %>
  </div>

  <% if action_name != "show" %>
    <%= render partial: 'shared/edit_and_delete_buttons', locals: { category: category } %>
  <% end %>
</section>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true, multipart: true, class: "flex flex-col justify-start items-start") do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 w-full text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
   
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>  

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 border-b w-[350px]">
    <%= f.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: 'Your name' %>
  </div>

  <div class="field flex justify-start w-full border-orange-300 my-8 items-center px-[2rem]">
    <% if category.new_record? %>
      <%= form.file_field :icon, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full', onchange: 'showPreview(event)' %>
    <% else %>
      <%= f.file_field :icon, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full', onchange: 'showPreview(event)' %>
    <% end %>
  </div> 

  <div id="preview-container" class="hidden my-8">
    <div class='border-2 p-4 border-dashed h-[300px] w-full flex justify-center items-center'>
      <img id="preview-image" src="#" alt="Image Preview" />
    </div>
  </div>

  <div class="inline">
    <%= f.submit "Save", class: "rounded py-3 px-8 text-base bg-green-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<script>
  function showPreview(event) {
    var file = event.target.files[0];
    var reader = new FileReader();
    var previewContainer = document.getElementById('preview-container');
    var previewImage = document.getElementById('preview-image');

    reader.onloadend = function() {
      previewImage.src = reader.result;
      previewContainer.classList.remove('hidden');
    }

    if (file) {
      reader.readAsDataURL(file);
    } else {
      previewImage.src = "";
      previewContainer.classList.add('hidden');
    }
  }
</script>

app/views/categories/edit.html.erb
<%= render partial: 'shared/header', locals: { heading: 'Edit Category', back: true } %>

<div class="w-full px-4">
  <%= render "form", category: @category %>
</div>

<%= render partial: 'shared/button', locals: { button_text: 'Back to categories', button_path: categories_path } %>

app/views/categories/index.html.erb
<div class="w-full border-orange-500 h-full">

  <%= render partial: 'shared/header', locals: { heading: 'categories', back: true } %>

  <div class='flex flex-col border-green-500 justify-start items-start pt-8 px-4'>
    <% if notice.present? %>
      <p class="py-2 px-3 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div id="categories" class="gap-4 flex flex-col justify-start items-center w-full border-amber-500 pb-10rem">
      <%= render @categories %>
    </div>

    <%= render partial: 'shared/button', locals: { button_text: 'Create new category', button_path: new_category_path } %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render partial: 'shared/header', locals: { heading: 'Create category', back: true } %>

<div class="px-4 border">
  <%= form_with(model: @category, local: true) do |form| %>
    <%= render "form", form: form, category: @category %>
  <% end %>

  <%= render partial: 'shared/button', locals: { button_text: 'Back to categories', button_path: categories_path } %>
</div>

app/views/categories/show.html.erb
<%= render partial: 'shared/header', locals: { heading: 'Transactions', back: true } %>

<div class="w-full">
  <div class="bg-gray-200">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div class='flex justify-between items-center py-8 px-4 bg-white'>
      <h1><%= @category.name %></h1>
      <p><strong>$</strong><%= @category.financial_transactions.sum(:amount) %></p>
    </div>
    <div class='bg-slate-100 p-4 px-4 flex flex-col justify-start items-center gap-4'>
      <% @category.financial_transactions.each do |transaction| %>
        <%= render partial: 'transactions/transaction', locals: { transaction: transaction } %>
      <% end %>
    </div>
  </div>
</div>

<%= render partial: 'shared/button', locals: { button_text: 'Create New Transaction', button_path: new_transaction_path } %>