config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  root "home#index"

  resources :categories
  resources :transactions

  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :categories
  has_many :transactions, foreign_key: 'author_id'

  # Validations
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[show edit update destroy]

  def index
    @transactions = Transaction.all
  end

  def show; end

  def new
    @transaction = Transaction.new
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.author = current_user

    respond_to do |format|
      if @transaction.save
        format.html do
          if @transaction.categories.any?
            redirect_to category_path(@transaction.categories.first), notice: 'Transaction created.'
          else
            redirect_to transactions_path, notice: 'Transaction created.'
          end
        end
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html do
          if @transaction.categories.any?
            redirect_to category_path(@transaction.categories.first), notice: 'Transaction successfully updated.'
          else
            redirect_to transactions_path, notice: 'Transaction updated but no category was associated.'
          end
        end
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Transaction deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find_by(id: params[:id])

    return if @transaction

    redirect_to categories_path, alert: 'Transaction not found.'
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, :image, :author_id, category_ids: [])
  end
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true, multipart: true, class: "contents") do |form| %>

  <% if transaction.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field flex justify-start w-full border-orange-300 my-8 items-center px-[2rem]">
    <%= form.file_field :image, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full', onchange: 'showPreview(event)' %>
  </div> 

  <div id="preview-container" class="hidden my-8">
    <div class='border-2 p-4 border-dashed h-[300px] w-full flex justify-center items-center'>
      <img id="preview-image" class='h-full w-full object-contain' src="#" alt="Image Preview" />
    </div>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_ids, "Category" %> <br>
    <div class="my-3">
      <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <div class="flex items-center">
          <%= cb.label(class: "mr-2") { cb.check_box + " " + cb.text } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="inline">
    <%= form.submit "Save Transaction", class: "rounded py-3 px-5 bg-green-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<script>
  function showPreview(event) {
    var file = event.target.files[0];
    var reader = new FileReader();
    var previewContainer = document.getElementById('preview-container');
    var previewImage = document.getElementById('preview-image');

    reader.onloadend = function() {
      previewImage.src = reader.result;
      previewContainer.classList.remove('hidden');
    }

    if (file) {
      reader.readAsDataURL(file);
    } else {
      previewImage.src = "";
      previewContainer.classList.add('hidden');
    }
  }
</script>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class='w-full'>
  <%= link_to transaction_path(transaction), class: "block" do %>
    <div class='flex bg-white border-orange-500 w-full p-3 py-4 justify-start items-center gap-4'>
      <div class="h-[70px] w-[70px] w-[20%] bg-slate-100 border-green-500 rounded flex justify-center items-center">
        <% if transaction.image.attached? %>
          <%= image_tag(url_for(transaction.image), alt: "Transaction Image", class: "fas fa-user fa-2x h-full w-full object-contain") %>
        <% else %>
          <i class="fas fa-user fa-2x"></i>
        <% end %>
      </div>
      <div class='bg-white rounded w-[] w-full border-orange-500'>
        <div class='flex justify-between items-center border-b'>
          <p class="my-4">
            <%= transaction.name %>
          </p>
          
          <p class="my-4 font-semibold">
            $<%= transaction.amount %>
          </p>
        </div>

        <p class="mt-2 text-sm font-light">
          <%= transaction.created_at.strftime("%d %b %Y") %>
        </p>
      </div>
    </div>
  <% end %>

  <% if action_name != "show" %>
    <%= link_to "Details", transaction, class: "rounded-lg py-2 text-white px-4 bg-green-500 inline-block font-medium" %>
    <%= link_to "Edit", edit_transaction_path(transaction), class: "rounded-lg py-2 ml-2 px-4 bg-gray-100 inline-block font-medium" %>
  <% end %>
</div>

app/views/transactions/edit.html.erb
  <%= render partial: 'shared/header', locals: { heading: 'Edit Transaction', back: true } %>
<div class="px-4 w-full">
  <%= render "form", transaction: @transaction %>
</div>

app/views/transactions/index.html.erb
<%= render partial: 'shared/header', locals: { heading: 'Transactions', back: true } %>

<div class="w-full px-4">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-end items-center mt-4 ">
    <%= link_to "New transaction", new_transaction_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="entities" class="min-w-full">
    <%= render @transactions %>
  </div>
</div>

app/views/transactions/new.html.erb
<%= render partial: 'shared/header', locals: { heading: 'new transaction', back: true } %>

<div class="px-4 w-full">
  <%= render "form", transaction: @transaction %>
</div>

app/views/transactions/show.html.erb
        <%= render partial: 'shared/header', locals: { heading: 'Details', back: true } %>

        <div class="mx-auto md:w-2/3 w-full px-4">
          <div class="mx-auto">
          <% if notice.present? %>
            <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
          <% end %>
          </div>
          <div class='w-full flex justify-start items-center gap-4 mt-4'>
            <div class='border h-[70px] w-[70px] rounded border border-orange-500 flex justify-center items-center'>
              <% if @transaction.image.attached? %>
                <%= image_tag(@transaction.image, alt: @transaction.name) %>
              <% else %>
                <i class="fas fa-user fa-2x"></i>
              <% end %>
            </div>
            <h1><%= @transaction.name %></h1>
          </div>

          <div class='text-secondary my-5'>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
          </div>
          <hr>
          <div class='my-5'>
            <p class='font-bold text-xl text-secondary'>Transaction No: <%= @transaction.id %></p>
            <p class="mt-4 text-sm font-light text-secondary">
              <i class="far fa-calendar-alt ml-2"></i>
              <%= @transaction.created_at.strftime("%d %b %Y") %> at <%= @transaction.created_at.strftime("%l:%M %P") %>
            </p>
          </div>
          <hr>

          <div class='flex justify-between items-center py-4 text-secondary'>
            <p class='font-semibold text-xl'>TOTAL PAYMENT</p>
            <p>$<%= @transaction.amount%></p>
          </div>
        </div>
      </div>
          
      <div class="inline-block ml-2 p-4 text-white flex justify-end items-center gap-4">
        <%= link_to "Edit", edit_transaction_path(@transaction), class: "mt-2 rounded py-3 px-5 bg-amber-500 inline-block font-medium" %>
        <%= button_to "Delete", transaction_path(@transaction), method: :delete, class: "mt-2 rounded py-3 px-5 bg-red-500 font-medium" %>
      </div>
      </div>
    </div>